pipeline:
  meu step custom:
    image: centos:7
    commands:
      - echo "hello world"
      - curl -X POST "POST -H "Content-Type: application/json" -d '{"text": "build ${DRONE_BUILD_NUMBER} executado com sucesso !"}' "https://chat.googleapis.com/v1/spaces/123/messages?key=123";"
